### ISSUE TITLE
Change Wording to Remove Trustless

### ISSUE THREAD

**Issue by super3** [StorjOld/storj.io#13]
Per this suggestion. http://www.reddit.com/r/Bitcoin/comments/22qivd/guys_here_is_storj_it_is_launching_soon_and_is/cgpfivb

**Comment by super3** [comment]
"Decentralized trust"
"Distributed trust"
"Allotted trust"
"Shared trust"
"Sectioned trust"

**Comment by jimlowry** [comment]
I prefer 
"automated"
"completely automated"
"automatic"
"computerized"
"robotic"

**Comment by jimlowry** [comment]
"Autonomous" is the word I chose to use instead of trustless in the whitepaper.  It fits.
