### ISSUE TITLE
Screenshot Scaling Issue

### ISSUE THREAD

**Issue by super3** [StorjOld/storj.io#23]
The screenshot should scale with the header, or disappear instead of being cut off. Looks worse on mobile. 
![https://i.imgur.com/NrfU95E.png](https://i.imgur.com/NrfU95E.png)

**Comment by robamichael** [comment]
This is the issue as experienced on a Nexus 4

![image](https://cloud.githubusercontent.com/assets/5054387/2963691/18dce928-dade-11e3-9fff-05f6ca439723.png)

**Comment by boshevski** [comment]
Fixed.
