### ISSUE TITLE
Broken 'Email' and 'Skype' Links On Website

### ISSUE THREAD

**Issue by ghost** [StorjOld/storj.io#37]
These tabs at the bottom of the Storj website (storj.io) do not work when clicked.

**Comment by EmergentBehavior** [comment]
Please mention any details you can to help diagnose this (e.g. OS, OS version, browser, browser version, what add-ons you have installed, if it works in any other browsers for you besides this one).

**Comment by ghost** [comment]
I am using Windows 8.1 and the latest version of Chrome. I have Ad Block, Ghostery, and PushBullet installed. I have tried disabling all of my add-ons but that did not solve the issue.

**Comment by ghost** [comment]
Also, it worked in my Safari.

**Comment by boshevski** [comment]
@mthompson362 There were some issues in Chrome regarding external links which should be fixed in the new version. Please update Chrome if you haven't already and check the website again.

**Comment by ghost** [comment]
@boshevski The links are working now. Thank you!
