### ISSUE TITLE
Typo in blog post

### ISSUE THREAD

**Issue by tomcatt360** [StorjOld/storj.io#59]
The blog post "How much will I make from DriveShare?" Has a typo in it. It says "GB" where it should say "TB":

![image](https://cloud.githubusercontent.com/assets/6033961/6420861/34cd3876-be87-11e4-834c-17a4737a1a77.png)

I am pretty sure 1 + 3*4 TB doesn't equal 13 GB. :P

~Thomas Parker

**Comment by EmergentBehavior** [comment]
~~Want to submit a pull request?~~ Actually, nevermind as the blog posts aren't hosted here. @boshevski can you update?

**Comment by nameone** [comment]
i can will do now.

**Comment by nameone** [comment]
All good now!

**Comment by EmergentBehavior** [comment]
Thanks @nameone

**Comment by tomcatt360** [comment]
You're welcome. I would have submitted a pull request if the blog was hosted here. Good catch, @EmergentBehavior !

~Thomas Parker
