### ISSUE TITLE
http://slack.storj.io/ Down

### ISSUE THREAD

**Issue by Velociraptor85** [StorjOld/storj.io#69]
Or at least I get an ERROR maybe its just me but an short check showed that it seems to be down for not only me?

**Comment by wirehiker** [comment]
No,it's not just you, I have the same problem, I hope it will get fixed soon. It's quite difficult to approach the all thing without a forum for information exachange.

**Comment by littleskunk** [comment]
https://slack.storj.io redirect to https://storj-inviter.herokuapp.com is working now. Everyone can join slack again :)
